import pygame


class ConstGraphic:
    background = pygame.image.load('./graphics/board.png')
    pawnBlack = pygame.image.load('./graphics/black.png')
    pawnWhite = pygame.image.load('./graphics/white.png')
    kingBlack = pygame.image.load('./graphics/black_king_crown.png')
    kingWhite = pygame.image.load('./graphics/white_king_crown.png')
    source = pygame.image.load('./graphics/source.png')
    destination = pygame.image.load('./graphics/destination.png')
    turnWhite = pygame.image.load('./graphics/buttons/white_to_move.png')
    turnBlack = pygame.image.load('./graphics/buttons/black_to_move.png')
    depth_3 = pygame.image.load('./graphics/buttons/depth_3.png')
    depth_5 = pygame.image.load('./graphics/buttons/depth_5.png')
    depth_8 = pygame.image.load('./graphics/buttons/depth_8.png')
    depth_3_click = pygame.image.load('./graphics/buttons/depth_3_click.png')
    depth_5_click = pygame.image.load('./graphics/buttons/depth_5_click.png')
    depth_8_click = pygame.image.load('./graphics/buttons/depth_8_click.png')
    exit = pygame.image.load('./graphics/buttons/exit_game.png')
    menu_bg = pygame.image.load('./graphics/buttons/menu_bg.png')
    game_bg = pygame.image.load('./graphics/buttons/game_bg.png')
    no_camera = pygame.image.load('./graphics/buttons/no_camera.png')
    no_camera_click = pygame.image.load('./graphics/buttons/no_camera_click.png')
    p_again = pygame.image.load('./graphics/buttons/play_again.png')
    p_ai = pygame.image.load('./graphics/buttons/play_ai.png')
    p_ai_click = pygame.image.load('./graphics/buttons/play_ai_click.png')
    p_human = pygame.image.load('./graphics/buttons/play_human.png')
    p_human_click = pygame.image.load('./graphics/buttons/play_human_click.png')
    r_black = pygame.image.load('./graphics/buttons/result_black.png')
    r_draw = pygame.image.load('./graphics/buttons/result_draw.png')
    r_white = pygame.image.load('./graphics/buttons/result_white.png')
    start = pygame.image.load('./graphics/buttons/start.png')
    w_camera = pygame.image.load('./graphics/buttons/with_camera.png')
    w_camera_click = pygame.image.load('./graphics/buttons/with_camera_click.png')
    evaluate = pygame.image.load('./graphics/buttons/evaluate.png')
    p_aswhite = pygame.image.load('./graphics/buttons/play_as_white.png')
    p_asblack = pygame.image.load('./graphics/buttons/play_as_black.png')

    